# Alternate site name
alternate: Watching Autumn

# Assets
statics: / #//cdn.jsdelivr.net/gh/username/RepositoryName@latest/
assets: assets
css: css
js: js
images: images

# themes/shoka/source/images/***
favicon:
  apple_touch_icon: /apple-touch-icon.png
  #safari_pinned_tab: /logo.svg
  #android_manifest: /manifest.json
  #ms_browserconfig: /browserconfig.xml

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

font:
  enable: true
  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Mulish
    size:

  # Font settings for alternate title.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # Font settings for site title.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: Noto Serif SC
    size:

  # Font settings for posts.
  posts:
    external: true
    family:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Inconsolata

# Dark Mode
# 根据用户选择是否使用夜间模式
# By default, the page judges whether to turn on the dark mode according to the device settings or user selection
# if `true`, the page will be displayed directly as Dark Mode, unless the user makes another choice
# 默认夜间模式是关闭的
darkmode: false

# By default the page will automatically scroll to the last viewed position
# if `false`, automatic positioning will be turned off 这个是自动保存浏览的位置下次打开继续到上一次浏览的位置
auto_scroll: true

# Whether to show the loading cat 是否显示加载时候旋转的那只猫
loader:
  start: false # When entering the page
  switch: false # When switching to another page

sidebar:
  # Sidebar Position. 导航栏的位置
  position: right
  # position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.jpg

menu:
  home: / || home
  about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || magic
  空间: /space/ || heart

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/Lklyx || github || "#191717"
  zhihu: https://www.zhihu.com/people/ci-qing-xiang-bei || zhihu || "#1e88e5"
  music: https://music.163.com/#/my/m/music/playlist?id=2475692347 || cloud-music || "#e60026"
  weibo: https://weibo.com/6872931730/profile?rightmod=1&wvr=6&mod=personnumber&is_all=1 || weibo || "#ea716e"
  about: https://about.me/yourname || address-card || "#3b5998"
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #google: https://plus.google.com/yourname || google
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

post:
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time 安装文章字数统计插件
  count: true #开启文章字数及阅读时间统计

# TagCloud settings for tags page.
tagcloud:
  # All values below are same as default, change them by yourself.
  min: 16 # Minimun font size in px
  max: 22 # Maxium font size in px
  start: "#72cecf" # Start color (hex, rgba, hsla or color keywords)
  end: "#ffbac3" # End color (hex, rgba, hsla or color keywords)
  amount: 200 # Amount of tags, change it if you have more than 200 tags

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2010
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true #开启文章字数及阅读时间统计
  powered: true

widgets:
  # if true, will show random posts
  random_posts: true
  # if true, will show recent comments
  recent_comments: true

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/share-your-work/licensing-types-examples
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
# CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
creative_commons:
  license: by-nc-sa
  language: deed.zh

# Reward (Donate)
# 赞赏功能
reward:
  # If true, reward will be displayed in every article by default.如果为真，则默认每篇文章中都会显示奖励
  enable: true
  account:
    wechatpay: /wechatpay.png #微信支付
    alipay: /alipay.png # 支付宝支付

# 添加文章加密
encrypt: # hexo-blog-encrypt
  enable: true
  abstract: 这里有东西被加密了，需要输入密码查看哦。
  message: 请输入密码查看，密码为6位数哦~。
  template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.


# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: false

# bgm
# audio: # 音频播放
  # - title: 列表1
  #   list:
  #    - https://music.163.com/#/playlist?id=2943811283
  #    - https://music.163.com/#/playlist?id=2297706586
  # - title: 列表2
  #   list:
  #    - https://music.163.com/#/playlist?id=2031842656
	
audio:
  - title: 醉倒温柔乡
    list: 
    - https://y.qq.com/n/yqq/playlist/7823950326.html
  - title: 古韵尤存
    list:
    - https://y.qq.com/n/yqq/playlist/2551805025.html
  - title: English-Songs # 英文歌单
    list:
    - https://y.qq.com/n/yqq/playlist/2644438503.html
  - title: 网易云
    list:
    - https://music.163.com/#/my/m/music/playlist?id=2475692347

# random image api
image_server: # "https://acg.xydwz.cn/api/api.php"

# Algolia Search
# For more information: https://www.algolia.com
search:
  hits:
    per_page: 10

# Comments
# Valine
# For more information: https://github.com/amehime/MiniValine
valine:
  appId: EXDYoCudeNtahPVAkKU3Xpvo-gzGzoHsz #Your_appId
  appKey: 0YheoTxWSKTMm6No3i5vYYig #Your_appkey
  placeholder: 留下你的足迹 # Comment box placeholder
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 8 # Pagination size
  lang: zh-CN
  visitor: true # Article reading statistic 文章访问量统计
  NoRecordIP: false # Whether to record the commenter IP 是否记录评论着的ip
  serverURLs: # https://yananduobu.top。启用自定义域名
  powerMode: true # 默认打开输入框的输入特效
  tagMeta:
    visitor: 新朋友
    master: 博主
    friend: 小伙伴
    investor: 金主大佬
  tagColor:
    visitor: "var(--color-orange)"
    master: "var(--primary-color)"
    friend: "var(--color-pink)"
    investor: "var(--color-pink)"
  tagMember:
    master:
      - 131ab989394372ace9fd15f9fc257a75
    friend:
      - friend@email.com
      - friend2@email.com
    investor:
      - investor1@email.com

# click with Firework

fireworks:
  enable: true
  color:
    - "rgba(255,182,185,.9)"
    - "rgba(250,227,217,.9)"
    - "rgba(187,222,214,.9)"
    - "rgba(138,198,209,.9)"

# Quicklink Support
# For more information: https://github.com/GoogleChromeLabs/quicklink
quicklink:
  # Custom a time in milliseconds by which the browser must execute prefetching.
  timeout: 3000
  # Default (true) will attempt to use the fetch() API if supported (rather than link[rel=prefetch]).
  priority: true

  # For more flexibility you can add some patterns (RegExp, Function, or Array) to ignores.
  # See: https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns
  ignores:

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------
baidu_analytics: # <app_id>

# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true

# Google Webmaster tools verification.
# See: https://www.google.com/webmasters
google_site_verification:

# Bing Webmaster tools verification.
# See: https://www.bing.com/webmaster
bing_site_verification:

# Yandex Webmaster tools verification.
# See: https://webmaster.yandex.ru
yandex_site_verification:

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO.
baidu_push: false


#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING `vendors` SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! Script dependencies will be combined with jsDelivr (cdn.jsdelivr.net)
#! ---------------------------------------------------------------
vendors:
  css:
    katex: npm/katex@0.12.0/dist/katex.min.css
    comment: css/comment.css
    fancybox: combine/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css,npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css
  js:
    pace: npm/pace-js@1.0.2/pace.min.js
    pjax: npm/pjax@0.2.8/pjax.min.js
    fetch: npm/whatwg-fetch@3.4.0/dist/fetch.umd.min.js
    anime: npm/animejs@3.2.0/lib/anime.min.js
    algolia: npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
    instantsearch: npm/instantsearch.js@4/dist/instantsearch.production.min.js
    lazyload: npm/lozad@1/dist/lozad.min.js
    quicklink: npm/quicklink@2/dist/quicklink.umd.js
    fancybox: combine/npm/jquery@3.5.1/dist/jquery.min.js,npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js,npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js
    valine: gh/amehime/MiniValine@4.2.2-beta10/dist/MiniValine.min.js
    copy_tex: npm/katex@0.12.0/dist/contrib/copy-tex.min.js
    chart: npm/frappe-charts@1.5.0/dist/frappe-charts.min.iife.min.js
